baseurl = "https://www.scriptstar.co.uk/"
languageCode = "en-us"
title = "Digital dairy of Narendra Mandadapu"
theme = "MorningPages"

[params]
  author = "Narendra Mandadapu"
  authorTitle = "Software Engineer"
	description = "Here I write about something about my thoughts and feelings"
	disqusShortname = "scriptstar"
	googleAnalytics = "UA-12249392-1"
	twitterId = "scriptstar"
	